Feat/jun/seachat tutorial multimedia upload
seasalt-ai/wiki pull request #100
Opened 2024-03-19 16:11 UTC by itIsJim

2024-03-19 23:35 UTC, xuchen requested changes
1. see my commit on multimedia and spreadsheet -- please get the chiense version translated
2. the order is reversed: 
![image](https://github.com/seasalt-ai/wiki/assets/543547/113e80e8-a1b1-45f6-bd31-3e37068f208b)
speadsheet should come before multimedia
3. please first pull to incorporate my changes, then commit on top of that

2024-03-19 23:35 UTC, xuchen commented on content/en/seachat/seachat-manual/03-add-knowledge/03-multimedia-upload.md
> +If you don't have a SeaChat account yet, you can sign up for free at [SeaChat website](https://chat.seasalt.ai/)! You can find all the information you need to create a knowledge-based chatbot in [Cre
let's not use the word `chatbot` or `bot`, please globally replace

2024-03-19 23:43 UTC, xuchen commented on content/en/seachat/seachat-manual/03-add-knowledge/02-spreadsheet-upload.md
>  SeaChat allows users to upload in bulk. You can see the status of each uploading file in the section below the drag-and-drop zone.
please be more specific: 
1. one can upload more than one excel
2. each excel can contain more than one worksheet

2024-03-20 19:09 UTC, amy17519 approved these changes

2024-03-20 19:35 UTC, xuchen approved these changes

2024-03-20 19:45 UTC, merged