feat/ KB additional setting en-zh wiki
seasalt-ai/wiki pull request #198
Opened 2024-05-31 18:06 UTC by itIsJim

2024-06-03 16:18 UTC, xuchen reviewed
In "Manual Entry" you've written about this PR:

![image](https://github.com/seasalt-ai/wiki/assets/543547/3fb2a35f-6972-406f-84e8-c9945e50297b)

Is there a reason to put it under "Additional Features"?

2024-06-03 16:29 UTC, xuchen commented
> @xuchen I put the wiki in the new section because i thought that it was related to the button setting which is under this section and it will also explain weights and other features related to KB.

but i don't understand why we can't write it in the original section? It's on the same page as the original section.

2024-06-03 16:32 UTC, itIsJim commented
@xuchen I can put the article back. I just moved it there to see if this arrangement was appropriate.

2024-06-03 16:38 UTC, xuchen commented
yeah pls put it back until you prove me wrong D:

2024-06-05 13:05 UTC, amy17519 commented
the screenshot here does not make sense. Please change to a better conversation example
<img width="684" alt="Screenshot 2024-06-05 at 21 04 24" src="https://github.com/seasalt-ai/wiki/assets/20276372/4ba643b9-ebbc-40e1-beb1-b805af15c976">

2024-06-05 13:06 UTC, amy17519 commented on content/en/seachat/seachat-manual/08-add-webpage-link-in-answers.md
> +You can also include relevant reference URLs in the AI assistant's responses, allowing users to access more detailed content or play related videos. In the **Existing Knowledge** page, you can find r
Delete `also`. 

Change `AI assistant` to `AI agent`

2024-06-05 13:21 UTC, amy17519 requested changes
We need to clarify a few things on this PR:

- [ ] This feature is specifically for KB. Please move it to under KB section
- [ ] This feature is not specially for Manual Entry. All KB document types can add URL as reference. Please rewrite the section where you mentioned only Manual Entry can reference URL.  
- [ ] We actually have 3 options for advanced settings for each KB document. This PR addresses only the first one: add URL. Please plan to the wiki structure to include also the other two features, or simply add them to this PR too.
<img width="1081" alt="Screenshot 2024-06-05 at 21 15 07" src="https://github.com/seasalt-ai/wiki/assets/20276372/b7758f42-405d-4b8c-8314-5c4819bdd8c8">
- [ ] The is a misunderstanding about the URL reference. The URL reference does not come from the answer directly. The URL reference is triggered when the corresponding KB document is retrieved as contextual information for current answer. So when you wrote `When the user asks a question that matches the answer you have added the URL to, the AI agent will display the answer with the URL button.`, this is actually a bit misleading. Please reread your description about the URL and then make this clear.

2024-06-07 18:23 UTC, xuchen commented
- [ ] change title to: "Adding buttons to KB responses"
- [ ] add more than 1 button
- [ ] explain that it's applicable to ALL existing documents

2024-06-14 16:29 UTC, xuchen approved these changes

2024-06-17 13:09 UTC, amy17519 approved these changes

2024-06-17 13:09 UTC, merged